version: '3.5'

services:

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity/Identity.Api/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  blog.api:
    image: ${DOCKER_REGISTRY-}blogapi
    build:
      context: .
      dockerfile: Blog/Blog.Api/Dockerfile
    depends_on:
      - sql.data
      - rabbitmq

  stats.api:
    image: ${DOCKER_REGISTRY-}statsapi
    build:
      context: .
      dockerfile: Stats/Stats.Api/Dockerfile
    depends_on:
       - nosql.data
       - rabbitmq

  notification.api:
    image: ${DOCKER_REGISTRY-}notificationapi
    build:
      context: .
      dockerfile: Notification/Notification.Api/Dockerfile
    depends_on:
      - rabbitmq
      
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway/Gateway.Api/Dockerfile
    depends_on:
      - sql.data
      - identity.api
      - blog.api