name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Identity/Identity.Api/Dockerfile
      run: docker build . --file Identity/Identity.Api/Dockerfile --tag ${DOCKER_REGISTRY-}identityapi
